drop table v_ACTIVITY; 
create table v_ACTIVITY as(
SELECT
      A.ACTIVITY_ID as ACTIVITY_ID,
      A.RECORD_ID AS ACTIVITY_RECORD_ID,
      A.MOLREGNO AS CPD_MOLREGNO,
      g.CHEMBL_ID as CPD_CHEMBL_ID,
      A.STANDARD_RELATION AS ACTIVITY_STANDARD_RELATION,
      A.STANDARD_VALUE AS ACTIVITY_STANDARD_VALUE,
      A.STANDARD_UNITS AS ACTIVITY_STANDARD_UNITS,
      A.STANDARD_FLAG AS ACTIVITY_STANDARD_FLAG,
      A.STANDARD_TYPE AS ACTIVITY_STANDARD_TYPE,
      A.ACTIVITY_COMMENT as ACTIVITY_ACTIVITY_COMMENT,
      A.DATA_VALIDITY_COMMENT AS ACTIVITY_DATA_VALIDITY_COMMENT,
      A.POTENTIAL_DUPLICATE AS ACTIVITY_POTENTIAL_DUPLICATE,
      a.PCHEMBL_VALUE  as ACTIVITY_PCHEMBL_VALUE,
      H.CHEMBL_ID as DOC_CHEMBL_ID,
      B.DESCRIPTION AS ASSAY_DESCRIPTION,
      d.ASSAY_DESC as ASSAY_TYPE,
      B.RELATIONSHIP_TYPE AS ASSAY_RELATIONSHIP_TYPE,
      B.ASSAY_TAX_ID AS ASSAY_TAX_ID,
      B.ASSAY_ORGANISM as ASSAY_ORGANISM,
      B.ASSAY_STRAIN as ASSAY_STRAIN,
      B.ASSAY_TEST_TYPE as ASSAY_TEST_TYPE,
      B.ASSAY_CATEGORY as ASSAY_CATEGORY,
      B.CONFIDENCE_SCORE AS ASSAY_CONFIDENCE_SCORE,
      b.CURATED_BY as ASSAY_CURATED_BY,
      B.CHEMBL_ID AS ASSAY_CHEMBL_ID,
      I.PREF_NAME as TISSUE_NAME,
      I.CHEMBL_ID as TISSUE_CHEMBL_ID,
      J.CELL_NAME as CELL_NAME,
      J.CHEMBL_ID as CELL_CHEMBL_ID,
      K.TARGET_TYPE as TARGET_TYPE,
      K.PREF_NAME AS TARGET_PREF_NAME,
      K.TAX_ID AS TARGET_TAX_ID,
      K.ORGANISM AS TARGET_ORGANISM,
      K.SPECIES_GROUP_FLAG AS TARGET_SPECIES_GROUP_FLAG,
      O.DOMAIN_NAME as TARGET_DOMAIN_NAME,
      O.DOMAIN_DESCRIPTION as TARGET_DOMAIN_DESC,
      M.COMPONENT_TYPE AS TARGET_COMP_TYPE,
      M.TAX_ID AS TARGET_COMP_TAX_ID,
      M.ORGANISM AS TARGET_COMP_ORGANISM,
      C.SHORT_NAME as PROTEIN_SHORT_NAME,
      C.DEFINITION AS PROTEIN_DEFINITION,
      C.CLASS_LEVEL AS PROTEIN_CLASS_LEVEL,
      L.HOMOLOGUE as TARGET_HOMOLOGUE,
      K.CHEMBL_ID AS TARGET_CHEMBL_ID,
      M.DESCRIPTION AS TARGET_COMP_DESC,
      M.ACCESSION AS TARGET_COMP_ACC,
      P.GO_ID as TARGET_COMP_GO_ID,
      Q.PATH as TARGET_COMP_GO_PATH
    FROM
        (((((((((((((((((ACTIVITIES A LEFT OUTER JOIN ASSAYS B ON A.ASSAY_ID = B.ASSAY_ID) 
        LEFT OUTER JOIN ASSAY_TYPE D ON D.ASSAY_TYPE = B.ASSAY_TYPE)
        LEFT OUTER JOIN BINDING_SITES E ON E.TID = B.TID)
        LEFT OUTER JOIN VIEW_COMPOUND_RECORDS F ON F.MOLREGNO = A.MOLREGNO)
        LEFT OUTER JOIN MOLECULE_DICTIONARY g ON g.MOLREGNO = a.MOLREGNO)
        LEFT OUTER JOIN DOCS H ON H.DOC_ID = A.DOC_ID)
        LEFT OUTER JOIN TISSUE_DICTIONARY I ON I.TISSUE_ID = B.TISSUE_ID)
        LEFT OUTER JOIN CELL_DICTIONARY J ON J.CELL_ID = B.CELL_ID)
        LEFT OUTER JOIN TARGET_DICTIONARY K ON K.TID = B.TID)
        LEFT OUTER JOIN TARGET_COMPONENTS L ON L.TID = K.TID)
        LEFT OUTER JOIN COMPONENT_SEQUENCES M ON M.COMPONENT_ID = L.COMPONENT_ID)
        LEFT OUTER JOIN SITE_COMPONENTS N ON N.COMPONENT_ID = M.COMPONENT_ID)
        LEFT OUTER JOIN domains O ON O.DOMAIN_ID = N.DOMAIN_ID)
        LEFT OUTER JOIN component_go P ON P.COMPONENT_ID = M.COMPONENT_ID)
        LEFT OUTER JOIN GO_CLASSIFICATION Q ON Q.GO_ID  = P.GO_ID)
        LEFT OUTER JOIN COMPONENT_CLASS R ON R.COMPONENT_ID = M.COMPONENT_ID)
        LEFT OUTER JOIN PROTEIN_CLASSIFICATION C ON C.PROTEIN_CLASS_ID = R.PROTEIN_CLASS_ID)
   where a.activity_id = 3419006 
)


