CREATE OR REPLACE VIEW VIEW_COMPOUND_RECORDS AS
SELECT
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT A.COMPOUND_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') COMPOUND_NAME,
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT A.COMPOUND_KEY || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') COMPOUND_KEY,
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT A.SRC_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') SRC_ID,
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT A.SRC_COMPOUND_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') SRC_COMPOUND_ID,
       A.MOLREGNO FROM COMPOUND_RECORDS A GROUP BY A.MOLREGNO;


CREATE OR REPLACE VIEW VIEW_COMP_SYNONYMS_GS AS
SELECT
       WM_CONCAT(COMPONENT_SYNONYM) AS COMPONENT_SYNONYM, A.COMPONENT_ID
FROM
       COMPONENT_SYNONYMS A
WHERE
       SYN_TYPE='GENE_SYMBOL'
GROUP BY
       A.COMPONENT_ID;


CREATE OR REPLACE VIEW VIEW_COMP_SYNONYMS_UNIPROT AS
SELECT
WM_CONCAT(COMPONENT_SYNONYM) AS COMPONENT_SYNONYM, A.COMPONENT_ID
FROM
       COMPONENT_SYNONYMS A
WHERE
       SYN_TYPE='UNIPROT'
GROUP BY
       A.COMPONENT_ID;


CREATE OR REPLACE VIEW VIEW_COMPONENT_GO AS
SELECT
       REPLACE(WM_CONCAT(GO_ID),',',';') AS GO_ID , M.COMPONENT_ID
FROM
       COMPONENT_GO M
GROUP BY
       M.COMPONENT_ID;


CREATE OR REPLACE VIEW VIEW_COMP_RECORDS_SOURCE AS
SELECT
       a.record_id,
       a.molregno,
       a.doc_id,
       a.compound_key,
       a.compound_name,
       a.src_id,
       a.src_compound_id,
       b.src_description,
       b.src_short_name
from COMPOUND_RECORDS a, SOURCE B WHERE A.SRC_ID = B.SRC_ID;



CREATE OR REPLACE VIEW VIEW_COMP_RECORDS_SOURCE_G AS
SELECT
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.compound_name || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') compound_name,
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.COMPOUND_KEY || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') COMPOUND_KEY,
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.SRC_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') SRC_ID,
       REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.SRC_COMPOUND_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') SRC_COMPOUND_ID,
       substr(RTRIM(XMLAGG(XMLPARSE(CONTENT a.src_description || ',' WELLFORMED)) .GETCLOBVAL(), ','),1,instr(RTRIM(XMLAGG(XMLPARSE(CONTENT a.src_description || ',' WELLFORMED)) .GETCLOBVAL(), ','),',')-1) src_description,
       substr(RTRIM(XMLAGG(XMLPARSE(CONTENT a.src_short_name || ',' WELLFORMED)) .GETCLOBVAL(), ','),1,instr(RTRIM(XMLAGG(XMLPARSE(CONTENT a.src_short_name || ',' WELLFORMED)) .GETCLOBVAL(), ','),',')-1) src_short_name,
       a.MOLREGNO from VIEW_COMP_RECORDS_source a group by a.MOLREGNO;



CREATE OR REPLACE VIEW VIEW_COMPONENTS_G AS
SELECT
            a.TID,
            StrClear(REPLACE(WM_CONCAT(HOMOLOGUE),',',';')) AS HOMOLOGUE,
            StrClear(REPLACE(WM_CONCAT(DOMAIN_NAME),',',';')) AS DOMAIN_NAME,
            StrClear(REPLACE(WM_CONCAT(DOMAIN_DESCRIPTION),',',';')) AS DOMAIN_DESCRIPTION,
            StrClear(REPLACE(WM_CONCAT(COMPONENT_TYPE),',',';')) AS COMPONENT_TYPE,
            StrClear(REPLACE(WM_CONCAT(TAX_ID),',',';')) AS TAX_ID,
            StrClear(REPLACE(WM_CONCAT(ORGANISM),',',';')) AS ORGANISM,
            StrClear(REPLACE(WM_CONCAT(SHORT_NAME),',',';')) as  SHORT_NAME,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.DEFINITION || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') DEFINITION,
            REPLACE(WM_CONCAT(CLASS_LEVEL),',',';') as  CLASS_LEVEL,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.DESCRIPTION || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') DESCRIPTION,
            REPLACE(WM_CONCAT(ACCESSION),',',';') as  ACCESSION,
            REPLACE(WM_CONCAT(GO_ID),',',';') as  GO_ID,
            REPLACE(WM_CONCAT(PATH),',',';') as  PATH
        FROM
            VIEW_COMPONENTS a
        GROUP BY
            a.TID;


CREATE OR REPLACE VIEW VIEW_COMPONENTS_G AS
SELECT
            a.TID,
            REPLACE(XMLAGG(XMLPARSE(CONTENT a.HOMOLOGUE || ',' WELLFORMED)) .GETCLOBVAL(), ',') HOMOLOGUE,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.DOMAIN_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') DOMAIN_NAME,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.DOMAIN_DESCRIPTION || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') DOMAIN_DESCRIPTION,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.COMPONENT_TYPE || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') COMPONENT_TYPE,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.TAX_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') TAX_ID,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.ORGANISM || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') ORGANISM,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.SHORT_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') SHORT_NAME,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.DEFINITION || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') DEFINITION,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.CLASS_LEVEL || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') CLASS_LEVEL,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.DESCRIPTION || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') DESCRIPTION,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.ACCESSION || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') ACCESSION,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.GO_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') GO_ID,
            REPLACE(RTRIM(XMLAGG(XMLPARSE(CONTENT a.PATH || ',' WELLFORMED)) .GETCLOBVAL(), ','),',',';') PATH
        FROM
            VIEW_COMPONENTS a
        GROUP BY
            a.TID;



CREATE OR REPLACE VIEW VIEW_COMPONENTS_GGG AS
SELECT
          a.TID,
          strcat(homologue) homologue,
          strcat(DOMAIN_NAME) DOMAIN_NAME,
          strcat(DOMAIN_DESCRIPTION) DOMAIN_DESCRIPTION,
          strcat(COMPONENT_TYPE) COMPONENT_TYPE,
          strcat(TAX_ID) TAX_ID,
          strcat(ORGANISM) ORGANISM,
          strcat(DEFINITION) DEFINITION,
          strcat(CLASS_LEVEL) CLASS_LEVEL,
          strcat(ACCESSION) ACCESSION,
          strcat(GO_ID) GO_ID,
          strcat(PATH) PATH,
          strcat(DESCRIPTION) DESCRIPTION,
          strcat(SHORT_NAME) SHORT_NAME
FROM
    VIEW_COMPONENTS a
GROUP BY
    a.TID;
