select 
  rm_same_str(strcat_clob(ACTIVITY_ID),',') as  ACTIVITY_ID,
  CPD_MOLREGNO,
  min(ACTIVITY_RECORD_ID) as  ACTIVITY_RECORD_ID,
  ASSAY_CHEMBL_ID,
  min(ACTIVITY_STANDARD_RELATION) as  ACTIVITY_STANDARD_RELATION,
  rm_same_str(strcat_clob(ACTIVITY_STANDARD_VALUE),',') as  ACTIVITY_STANDARD_VALUE,
  min(ACTIVITY_PCHEMBL_VALUE) as  ACTIVITY_PCHEMBL_VALUE,
  min(ACTIVITY_STANDARD_TYPE) as  ACTIVITY_STANDARD_TYPE,
  min(ACTIVITY_EFFICIACY) as  ACTIVITY_EFFICIACY,
  min(ACTIVITY_STANDARD_UNITS) as  ACTIVITY_STANDARD_UNITS,
  min(ACTIVITY_STANDARD_FLAG) as  ACTIVITY_STANDARD_FLAG,
  min(ACTIVITY_ACTIVITY_COMMENT) as  ACTIVITY_ACTIVITY_COMMENT,
  min(ACTIVITY_DATA_VALIDITY_COMMENT) as  ACTIVITY_DATA_VALIDITY_COMMENT,
  min(ACTIVITY_POTENTIAL_DUPLICATE) as  ACTIVITY_POTENTIAL_DUPLICATE,
  min(ASSAY_DESCRIPTION) as  ASSAY_DESCRIPTION,
  min(ASSAY_TYPE) as  ASSAY_TYPE,
  min(ASSAY_STRAIN) as  ASSAY_STRAIN,
  min(ASSAY_STRAIN) as  ASSAY_TEST_TYPE,
  min(ASSAY_STRAIN) as  ASSAY_CATEGORY,
  min(ASSAY_STRAIN) as  ASSAY_CONFIDENCE_SCORE,
  min(ASSAY_STRAIN) as  ASSAY_CURATED_BY,
  min(TISSUE_NAME) as  TISSUE_NAME,
  min(CELL_NAME) as  CELL_NAME,
  min(TARGET_TYPE) as  TARGET_TYPE,
  min(TARGET_PREF_NAME) as  TARGET_PREF_NAME,
  min(TARGET_TAX_ID) as  TARGET_TAX_ID,
  min(TARGET_ORGANISM) as  TARGET_ORGANISM,
  min(TARGET_SPECIES_GROUP_FLAG) as  TARGET_SPECIES_GROUP_FLAG,
  min(TARGET_DOMAIN_NAME) as  TARGET_DOMAIN_NAME,
  min(TARGET_DOMAIN_DESC) as  TARGET_DOMAIN_DESC,
  min(TARGET_COMP_TYPE) as  TARGET_COMP_TYPE,
  min(TARGET_COMP_TAX_ID) as  TARGET_COMP_TAX_ID,
  min(TARGET_COMP_ORGANISM) as  TARGET_COMP_ORGANISM,
  min(CPD_CHEMBL_ID) as  CPD_CHEMBL_ID,
  min(TISSUE_CHEMBL_ID) as  TISSUE_CHEMBL_ID,
  min(CELL_CHEMBL_ID) as  CELL_CHEMBL_ID,
  min(DOC_CHEMBL_ID) as  DOC_CHEMBL_ID,
  '  ' AS INVALID

from  (

  SELECT
    A.ACTIVITY_ID AS ACTIVITY_ID,
    A.RECORD_ID AS ACTIVITY_RECORD_ID,
    A.MOLREGNO AS CPD_MOLREGNO,
    A.STANDARD_RELATION AS ACTIVITY_STANDARD_RELATION,
    A.STANDARD_VALUE AS ACTIVITY_STANDARD_VALUE,
    A.PCHEMBL_VALUE  AS ACTIVITY_PCHEMBL_VALUE,
    a.STANDARD_TYPE as ACTIVITY_STANDARD_TYPE,
    ( case when a.STANDARD_TYPE='Efficacy' then a.STANDARD_VALUE else null end)  as ACTIVITY_EFFICIACY,
    A.STANDARD_UNITS AS ACTIVITY_STANDARD_UNITS,
    A.STANDARD_FLAG AS ACTIVITY_STANDARD_FLAG,
    A.ACTIVITY_COMMENT AS ACTIVITY_ACTIVITY_COMMENT,
    A.DATA_VALIDITY_COMMENT AS ACTIVITY_DATA_VALIDITY_COMMENT,
    A.POTENTIAL_DUPLICATE AS ACTIVITY_POTENTIAL_DUPLICATE,
    B.DESCRIPTION AS ASSAY_DESCRIPTION,
    D.ASSAY_DESC AS ASSAY_TYPE,
    B.RELATIONSHIP_TYPE AS ASSAY_RELATIONSHIP_TYPE,
    B.ASSAY_STRAIN AS ASSAY_STRAIN,
    B.ASSAY_TEST_TYPE AS ASSAY_TEST_TYPE,
    B.ASSAY_CATEGORY AS ASSAY_CATEGORY,
    B.CONFIDENCE_SCORE AS ASSAY_CONFIDENCE_SCORE,
    B.CURATED_BY AS ASSAY_CURATED_BY,
    I.PREF_NAME AS TISSUE_NAME,
    J.CELL_NAME AS CELL_NAME,
    K.TARGET_TYPE AS TARGET_TYPE,
    K.PREF_NAME AS TARGET_PREF_NAME,
    K.TAX_ID AS TARGET_TAX_ID,
    K.ORGANISM AS TARGET_ORGANISM,
    K.SPECIES_GROUP_FLAG AS TARGET_SPECIES_GROUP_FLAG,
    O.DOMAIN_NAME AS TARGET_DOMAIN_NAME,
    O.DOMAIN_DESCRIPTION AS TARGET_DOMAIN_DESC,
    M.COMPONENT_TYPE AS TARGET_COMP_TYPE,
    M.TAX_ID AS TARGET_COMP_TAX_ID,
    M.ORGANISM AS TARGET_COMP_ORGANISM,
    G.CHEMBL_ID AS CPD_CHEMBL_ID,
    B.CHEMBL_ID AS ASSAY_CHEMBL_ID,
    I.CHEMBL_ID AS TISSUE_CHEMBL_ID,
    J.CHEMBL_ID AS CELL_CHEMBL_ID,
    H.CHEMBL_ID AS DOC_CHEMBL_ID,
    ( case when a.STANDARD_relation ='>' then 'NEG_RESP'
               when  a.STANDARD_relation ='=' then to_char(a.standard_value)
               else null end )  as ec_response_neg

FROM
    (((((((((((((ACTIVITIES A LEFT OUTER JOIN ASSAYS B ON A.ASSAY_ID = B.ASSAY_ID)
    LEFT OUTER JOIN ASSAY_TYPE D ON D.ASSAY_TYPE = B.ASSAY_TYPE)
    LEFT OUTER JOIN MOLECULE_DICTIONARY G ON G.MOLREGNO = A.MOLREGNO)
    LEFT OUTER JOIN DOCS H ON H.DOC_ID = A.DOC_ID)
    LEFT OUTER JOIN TISSUE_DICTIONARY I ON I.TISSUE_ID = B.TISSUE_ID)
    LEFT OUTER JOIN CELL_DICTIONARY J ON J.CELL_ID = B.CELL_ID)
    LEFT OUTER JOIN TARGET_DICTIONARY K ON K.TID = B.TID)
    LEFT OUTER JOIN TARGET_COMPONENTS L ON L.TID = K.TID)
    LEFT OUTER JOIN COMPONENT_SEQUENCES M ON M.COMPONENT_ID = L.COMPONENT_ID)
    LEFT OUTER JOIN SITE_COMPONENTS N ON N.COMPONENT_ID = M.COMPONENT_ID)
    LEFT OUTER JOIN DOMAINS O ON O.DOMAIN_ID = N.DOMAIN_ID)
    left outer join component_class r on r.component_id = m.component_id)
    left outer join protein_classification c on c.protein_class_id = r.protein_class_id)
where
    a.record_id in (
        select distinct( a.record_id) from ACTIVITIES A where a.standard_type = 'Efficacy' )
    and ((a.pchembl_value is not null) or ((a.standard_type = 'Efficacy') and (a.STANDARD_VALUE is not null)) or  (a.standard_relation = '>')  )

) t 

group by CPD_MOLREGNO, ASSAY_CHEMBL_ID, ACTIVITY_STANDARD_TYPE
