drop table v_assay_extract; 
create table v_assay_extract as(


select 
  ACTIVITY_RECORD_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT CPD_MOLREGNO || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  CPD_MOLREGNO,
  max(ACTIVITY_STANDARD_RELATION) AS ACTIVITY_STANDARD_RELATION,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_STANDARD_VALUE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_STANDARD_VALUE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_PCHEMBL_VALUE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_PCHEMBL_VALUE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_STANDARD_TYPE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_STANDARD_TYPE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_EFFICIACY || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_EFFICIACY,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_STANDARD_UNITS || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_STANDARD_UNITS,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_STANDARD_FLAG || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_STANDARD_FLAG,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_ACTIVITY_COMMENT || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_ACTIVITY_COMMENT,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ACTIVITY_DATA_VALIDITY_COMMENT || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ACTIVITY_DATA_VALIDITY_COMMENT,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_DESCRIPTION || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_DESCRIPTION,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_TYPE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_TYPE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_RELATIONSHIP_TYPE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_RELATIONSHIP_TYPE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_STRAIN || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_STRAIN,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_TEST_TYPE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_TEST_TYPE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_CATEGORY || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_CATEGORY,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_CONFIDENCE_SCORE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_CONFIDENCE_SCORE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_CURATED_BY || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_CURATED_BY,
  
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TISSUE_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TISSUE_NAME,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT CELL_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  CELL_NAME,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_TYPE || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_TYPE,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_PREF_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_PREF_NAME,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_TAX_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_TAX_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_SPECIES_GROUP_FLAG || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_SPECIES_GROUP_FLAG,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_DOMAIN_NAME || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_DOMAIN_NAME,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_DOMAIN_DESC || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_DOMAIN_DESC,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_COMP_TAX_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_COMP_TAX_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TARGET_COMP_ORGANISM || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TARGET_COMP_ORGANISM,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT CPD_CHEMBL_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  CPD_CHEMBL_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT ASSAY_CHEMBL_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  ASSAY_CHEMBL_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT TISSUE_CHEMBL_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  TISSUE_CHEMBL_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT CELL_CHEMBL_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  CELL_CHEMBL_ID,
  replace(rm_same_str(RTRIM(XMLAGG(XMLPARSE(CONTENT DOC_CHEMBL_ID || ',' WELLFORMED)) .GETCLOBVAL(), ','),','),',',';') as  DOC_CHEMBL_ID,
  '' AS INVALID
  
  
from  (

SELECT 
    A.ACTIVITY_ID AS ACTIVITY_ID,
    A.RECORD_ID AS ACTIVITY_RECORD_ID,
    A.MOLREGNO AS CPD_MOLREGNO,
    A.STANDARD_RELATION AS ACTIVITY_STANDARD_RELATION,
    A.STANDARD_VALUE AS ACTIVITY_STANDARD_VALUE,
    A.PCHEMBL_VALUE  AS ACTIVITY_PCHEMBL_VALUE,
    a.STANDARD_TYPE as ACTIVITY_STANDARD_TYPE,
    ( case when a.STANDARD_TYPE='Efficacy' then a.STANDARD_VALUE else null end)  as ACTIVITY_EFFICIACY,
    A.STANDARD_UNITS AS ACTIVITY_STANDARD_UNITS,
    A.STANDARD_FLAG AS ACTIVITY_STANDARD_FLAG,
    A.ACTIVITY_COMMENT AS ACTIVITY_ACTIVITY_COMMENT,
    A.DATA_VALIDITY_COMMENT AS ACTIVITY_DATA_VALIDITY_COMMENT,
    A.POTENTIAL_DUPLICATE AS ACTIVITY_POTENTIAL_DUPLICATE,
    B.DESCRIPTION AS ASSAY_DESCRIPTION,
    D.ASSAY_DESC AS ASSAY_TYPE,
    B.RELATIONSHIP_TYPE AS ASSAY_RELATIONSHIP_TYPE,
    B.ASSAY_STRAIN AS ASSAY_STRAIN,
    B.ASSAY_TEST_TYPE AS ASSAY_TEST_TYPE,
    B.ASSAY_CATEGORY AS ASSAY_CATEGORY,
    B.CONFIDENCE_SCORE AS ASSAY_CONFIDENCE_SCORE,
    B.CURATED_BY AS ASSAY_CURATED_BY,
    I.PREF_NAME AS TISSUE_NAME,
    J.CELL_NAME AS CELL_NAME,
    K.TARGET_TYPE AS TARGET_TYPE,
    K.PREF_NAME AS TARGET_PREF_NAME,
    K.TAX_ID AS TARGET_TAX_ID,
    K.ORGANISM AS TARGET_ORGANISM,
    K.SPECIES_GROUP_FLAG AS TARGET_SPECIES_GROUP_FLAG,
    O.DOMAIN_NAME AS TARGET_DOMAIN_NAME,
    O.DOMAIN_DESCRIPTION AS TARGET_DOMAIN_DESC,
    M.COMPONENT_TYPE AS TARGET_COMP_TYPE,
    M.TAX_ID AS TARGET_COMP_TAX_ID,
    M.ORGANISM AS TARGET_COMP_ORGANISM,
    G.CHEMBL_ID AS CPD_CHEMBL_ID,
    B.CHEMBL_ID AS ASSAY_CHEMBL_ID,
    I.CHEMBL_ID AS TISSUE_CHEMBL_ID,
    J.CHEMBL_ID AS CELL_CHEMBL_ID,
    H.CHEMBL_ID AS DOC_CHEMBL_ID,
    '' AS INVALID
FROM   
    (((((((((((ACTIVITIES A LEFT OUTER JOIN ASSAYS B ON A.ASSAY_ID = B.ASSAY_ID) 
    LEFT OUTER JOIN ASSAY_TYPE D ON D.ASSAY_TYPE = B.ASSAY_TYPE)
    LEFT OUTER JOIN MOLECULE_DICTIONARY G ON G.MOLREGNO = A.MOLREGNO)
    LEFT OUTER JOIN DOCS H ON H.DOC_ID = A.DOC_ID)
    LEFT OUTER JOIN TISSUE_DICTIONARY I ON I.TISSUE_ID = B.TISSUE_ID)
    LEFT OUTER JOIN CELL_DICTIONARY J ON J.CELL_ID = B.CELL_ID)
    LEFT OUTER JOIN TARGET_DICTIONARY K ON K.TID = B.TID)
    LEFT OUTER JOIN TARGET_COMPONENTS L ON L.TID = K.TID)
    LEFT OUTER JOIN COMPONENT_SEQUENCES M ON M.COMPONENT_ID = L.COMPONENT_ID)
    LEFT OUTER JOIN SITE_COMPONENTS N ON N.COMPONENT_ID = M.COMPONENT_ID)
    LEFT OUTER JOIN DOMAINS O ON O.DOMAIN_ID = N.DOMAIN_ID)
where
    a.record_id in (select distinct( a.record_id) from ACTIVITIES A where a.standard_type = 'Efficacy' ) and 
    ( (a.pchembl_value is not null) or (a.standard_type = 'Efficacy') )
) v
group by v.ACTIVITY_RECORD_ID


)